# Generated by Django 6.0.2 on 2026-02-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_add_allergens'),
        ('users', '0003_remove_customuser_fist_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='excluded_allergens',
            field=models.ManyToManyField(blank=True, related_name='users_excluding', to='main.allergen', verbose_name='исключить аллергены'),
        ),
    ]
