# Generated by Django 6.0.1 on 2026-01-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='dishes/main/'),
        ),
    ]
