# Generated by Django 6.0.1 on 2026-02-06 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True, validators=[django.core.validators.RegexValidator(regex='^[-\\wа-яА-ЯёЁ]+$')]),
        ),
    ]
