# Generated by Django 6.0.1 on 2026-02-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_dish_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
