# Generated by Django 6.0.1 on 2026-01-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_dish_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='main_image',
            field=models.ImageField(upload_to='dishes/main/'),
        ),
    ]
