# Generated by Django 6.0.1 on 2026-01-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_dish_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='dish',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='dishes/main/'),
        ),
    ]
